### ISSUE TITLE
Openplotter integration tread

### ISSUE THREAD

**Issue by FredericGuilbault** [lysmarine/lysmarine_gen#1]
Here all the notes and links for the ongoing process of integrating openplotter into lysmarine.

**Comment by FredericGuilbault** [comment]
The issues I have reported to sailoog are going to be fixed in the 2.x.x version.

**Comment by FredericGuilbault** [comment]
There are pull request open

**Comment by mgrouch** [comment]
Might be openplotter is not needed.
It was very useful for sometime. 
It’s just bunch of scripts for setting things up. If we recognize know hardware it might be not needed. 
At least I would hold on on integrating

**Comment by FredericGuilbault** [comment]
yeah, it's mainly there cuz it's a possibility to implement and I have no plan to do it my self.   They still don't do things "the linux way" although they made great improvement since their first version and that will break stuff.
