### ISSUE TITLE
Show onboard on screen lock

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#101]
Show onboard on screen lock. Otherwise there is no way to enter password on touchscreen

**Comment by FredericGuilbault** [comment]
The screen should not lock. That's the source of the problem.

**Comment by FredericGuilbault** [comment]
Wait.... Openbox does not have a session locker..... How do you make that happen ???

**Comment by mgrouch** [comment]
Budgie

**Comment by FredericGuilbault** [comment]
Lysmarine will not packag budgie until you make a pull request. Therefore, this issue does not belong to this repository.
