### ISSUE TITLE
Text consoles are missing a cursor

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#102]
Text consoles are missing a cursor

**Comment by FredericGuilbault** [comment]
U mean in lxterm under openbox ?

**Comment by mgrouch** [comment]
not GUI ones. the text ones. Ctrl-Alt-F1/2/3/4 etc 
real console

**Comment by mgrouch** [comment]
Well. I’ve merged this fix into my fork and still have same issue. It didn’t fix it for me
