### ISSUE TITLE
Base lysmarine image on Ubuntu groovy 

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#109]
Base lysmarine image on Ubuntu groovy. Raspberry OS uses old kernel and old Debian buster stuff, which shows its age. It would be nice to have a build based on something modern. Might be anbox would work on it. Groovy gorilla Ubuntu image is available and has way more up to date packages. It would be nice to start having lysmarine build image against it

**Comment by FredericGuilbault** [comment]
lol buster is not old.    

But yeah, Debian prefer stability to shiny features and Lysmarine will stick with debian. That's a core point of the project. 

 - Debian is more stable. 
 - Debian don't break retro-compatibility
 - Debian is the base of Most SBC OS
 - Debian have the largest base of skilled users.
 
 I would go with ArchLinux before Ubuntu in terms of quality OS with all the latest versions of everything.
