### ISSUE TITLE
Boots into CLI, no desktop

### ISSUE THREAD

**Issue by deanfourie1** [lysmarine/lysmarine_gen#119]
Upon every boot, I get "Desktop Starting" then it just hands at cli.

A manual startx opens the desktop manually. 

Is there a way to start on boot automatically?

Thanks

**Comment by FredericGuilbault** [comment]
This is strange, It should start automatically via the systemd [service unit called startx](
https://github.com/lysmarine/service_manager/blob/master/servicemanager/startx.service). 


Have you try  `systemctl start startx` and `systemctl enable startx`   ?

**Comment by deanfourie1** [comment]
It does start, I was just being too impatient. Also as per the documentation I see there is a way to skip this and login straight into the X session. Sorry but this is resolved!
