### ISSUE TITLE
Opencpn config window have no scrool bar. 

### ISSUE THREAD

**Issue by FredericGuilbault** [lysmarine/lysmarine_gen#24]
On 0.8.2,  
> Opencpn baud rate setting is not reachable due to window not expandable. 

Original report At https://www.facebook.com/lysmarineOS/posts/869226120085583

**Comment by mgrouch** [comment]
No longer an issue. With latest OpenCPN I could scroll with just  dragging finger over the form.

**Comment by FredericGuilbault** [comment]
Yep. Thx for reviewing it.
