### ISSUE TITLE
add music server (mopidy)

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#26]
See https://bareboat-necessities.github.io/my-bareboat/#_music_player

It needs its own unix user account
and registers are a service

**Comment by mgrouch** [comment]
Added in my fork. 
No yet support for Spotify. 
Needs more config for YouTube music.

**Comment by mgrouch** [comment]
Still needs more work to support pulseaudio sound mixer.

**Comment by FredericGuilbault** [comment]
I would take a pull request concerning this specific feature. That would be a nice feature.

**Comment by mgrouch** [comment]
Some nice tips here

https://www.raspberrypi.org/forums/viewtopic.php?t=274113

if you installed chromium, make sure its "rpi-chromium-mods" thats the optimized version.
add "chromium-browser --headless" to startup, preloads chromium, shortens first startup lag.

**Comment by mgrouch** [comment]
Is there any reason you are using pulseaudio as opposed to just alsa?
Pulseaudio adds additional configuration hurdles.

**Comment by FredericGuilbault** [comment]
No real reasons.

**Comment by FredericGuilbault** [comment]
I think mopidy should be somewhere in the `4-server` stage as it's web based and can easily be used without a screen attached to the RPI

**Comment by mgrouch** [comment]
True

**Comment by mgrouch** [comment]
Same with avnav and ppp-modem for iridium

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Done in my fork
