### ISSUE TITLE
Please use UbuntuFonts on desktop (menus, forms, etc) They are much more readable on small touchscreens in a cockpit

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#28]
Please use Ubuntu Fonts on desktop theme (menus, forms, etc) They are much more readable on small touchscreens in a cockpit
(than the fonts raspberry OS is using)

sudo apt-get -y install fonts-ubuntu

And the default theme should be dark like on most smartphones.

Breeze-Dark is a nice theme. I've played with many,

sudo aapt-get -y install breeze-gtk-theme breeze-icon-theme breeze-icon-theme breeze-icon-theme-rcc breeze-cursor-theme

Start lxappearance

lxappearance

and choose 'Breeze-Dark' 

Thanks,
--MG

**Comment by FredericGuilbault** [comment]
fonts-ubuntu is a non-free package under debian, I have no problem with this, it only means that implementing this will include modifying the apt source.list 

---

breeze-gtk theme would be better than what I use ATM. But there is something that don't show right in Opencpn. I think This must be fixed before the white square is white on white. 
![image](https://user-images.githubusercontent.com/37122999/97241134-8ce95f00-17c6-11eb-8586-26e515b3440e.png)

---

**Comment by mgrouch** [comment]
Sans is a good font
Just use it consistently
