### ISSUE TITLE
UDP vs TCP for NMEA

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#30]
UDP I think would be a better choice for LAN NMEA network traffic than TCP.
UDP is connectionless so it restores automatically, while I've seen 
bugs in SignalK or something else where it wouldn't restore lost TCP connections.

Thanks,
--MG

**Comment by FredericGuilbault** [comment]
Hummmm, that's a good question. 

On the other hand, A big part of the UDP design is: if anything go wrong, Drop the package and move forward.   

This mean causing dataloss just to keep in sync( in terms of milliseconds) with the emitter. 


But really, I'm not knowledgeable enough in this domain to have an opinion on what would be the best.

**Comment by FredericGuilbault** [comment]
I asked the question signalk usergroup 
https://groups.google.com/g/signalk/c/uKwSHLbEES4/m/yGD5PPsXCAAJ

**Comment by FredericGuilbault** [comment]
As on lysmarine every data flow should go thru signalk, this is the plugin that need to be configured to enable udp nmea communication. 

https://www.npmjs.com/package/@signalk/udp-nmea-plugin

Now the task would be to add it and configure it in the build script.

**Comment by mgrouch** [comment]
Close for now
