### ISSUE TITLE
Some kind of protection from running out of disk space is needed

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#31]
Some kind of protection from running out of disk space is needed

Thanks

**Comment by FredericGuilbault** [comment]
I never tested it but I just came across a software named  stracer it seem to have allert and service management/ 

+ a web interface which is sexy 

https://github.com/oguzhaninan/Stacer

**Comment by FredericGuilbault** [comment]
I tried stacer and it's a no-go 
![image](https://user-images.githubusercontent.com/37122999/101969983-a8cd8680-3bf5-11eb-8267-70b43d4db8fb.png)

Eating 7% of a core of my i7-4200 CPU while the window closed and the machine idle make no sense to me.

**Comment by FredericGuilbault** [comment]
Awesomewm have a disk usage bar.
