### ISSUE TITLE
Better default setting and styling of OnBoard on screen keyboard

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#37]
Better default setting and styling of OnBoard on screen keyboard
to match the default desktop theme, fonts, etc

**Comment by mgrouch** [comment]
Use same Sans font for key labels as on desktop

**Comment by FredericGuilbault** [comment]
There is a missing newline in ./config/openbox/autostart that break the config injection for onboard. 

This is what you should see: 
![image](https://user-images.githubusercontent.com/37122999/99458392-75e7e980-28fa-11eb-9ec1-18797b5b583e.png)

are you seeing this or the fullscreen whit one ?

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Related commits found by digging git-blame :

https://github.com/bareboat-necessities/lysmarine_gen/commit/eb6d5ab93d62279ca8222218bb356f837999c6a1
https://github.com/bareboat-necessities/lysmarine_gen/commit/b97fa81be79ec96da893fd1f5a7bd80925a55af2
https://github.com/bareboat-necessities/lysmarine_gen/commit/0d61409ee2de3d961f36d6bc96da08efd7f98be7
https://github.com/bareboat-necessities/lysmarine_gen/commit/0d61409ee2de3d961f36d6bc96da08efd7f98be7

**Comment by FredericGuilbault** [comment]
fixed here : 
fc6606cadda0b603f93ef7a755992342840ca493
0b3b9ea4e962814a6738b5f94217bcc491e281e4
