### ISSUE TITLE
Consider adding some GIS geospacial database and GIS front end UI app 

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#39]
Examples

PostGIS

QGIS

Thanks

**Comment by FredericGuilbault** [comment]
What would be the advantage of this. I mean what need does it solve ??? 
__
I try to install sasPlanet via PlayOnLinux before, to webscrape navionics web-app charts in mbtiles format. It worked but the RPI was too slow to manage such dataset. So I dropped the idea as it would be more painful than useful for an embeded chartplotter.

**Comment by mgrouch** [comment]
Not a priority I think
