### ISSUE TITLE
Install caching HTTP proxy for known free map tiling servers

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#43]
Install caching HTTP proxy for known free map tiling servers
To reduce the traffic so previously downloaded tiles would be cached 
on local filesystem

**Comment by mgrouch** [comment]
I think it not a priority

**Comment by FredericGuilbault** [comment]
I also think this quite not a priority.... But why you open so much issue if you just close them after a second thought. ???

This is not your personal notepad or the issue tab of your hard-fork....  You know I'm taking time to read, try to understand and sort all of this and this time is forever lost. No value is added to the product while I'm on Github managing the issue tab.
