### ISSUE TITLE
[Known problem] WxWidgets issues with dark themes

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#44]
WxWidgets issues with dark themes

tracked here

https://trac.wxwidgets.org/ticket/18941

**Comment by FredericGuilbault** [comment]
AFAIK WxWidgets is a dependency of https://github.com/pypilot/pypilot only Ill wait for @Sean to update it's software.

**Comment by mgrouch** [comment]
at least workaround in lysmarine would be not to use dark themes on gtk2 apps

**Comment by FredericGuilbault** [comment]
now that lxpanel and few others use gtk3,  Do you know how could I check if anything else is using gtk2 ?

**Comment by mgrouch** [comment]
ldd <executable-path> | grep gtk

**Comment by FredericGuilbault** [comment]
I did what I can to move away to gtk2, for the rest it's out of my capacity. We will have to wait for upstream fixes or someone willing to that that further.
