### ISSUE TITLE
Have a set of Usefull marine related bookmarks in chromium. 

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#47]
Dockwa marina booking app on desktop needed

**Comment by mgrouch** [comment]
Seems could be added via nativfier

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Having remote services shown as desktop app will make it look broken as soon as there it no connection.

Also does nativfier handle the signu p/login  have you tested ? 

And why Dockwa over any of its competitor ?

**Comment by mgrouch** [comment]
Might just add one static page with a button to one of web servers we running (SignalK ?)
Which will show status online / offline and let proceed if dockwa is accessible on-line
