### ISSUE TITLE
set video memory split and install openCPN with OpenGL ENABLED by default

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#50]
set video memory split and install openCPN with OpenGL ENABLED by default

**Comment by mgrouch** [comment]
I've done changes to default to OpenGL for OpenCPN. 
See my fork of lymarine-gen

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Not every SBC support OpenGL 3.X I remember opencpn making  RPi 2 crashing when activating it. 

We would need a way to detect the support before blindly activating this feature.
