### ISSUE TITLE
Style window decorations (close/minimize/maximize) so that they apart from each other for better touch support

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#55]
Style window decorations (close/minimize/maximize) so that they apart from each other for better touch support

**Comment by mgrouch** [comment]
Making window title bar font 16pt fixes it.

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Solved by the change to awesomewm
