### ISSUE TITLE
onboard missing dependencies

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#61]
It needs to be installed like this

apt-get install -y onboard dconf-cli dbus-x11 at-spi2-core mousetweaks acpid

at-spi2-core mousetweaks acpid

do not come if python packages are installed with --no-install-recommends

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
What does it solve ?

**Comment by mgrouch** [comment]
Size of the image. I’ve disabled recommended packages for python ones and it lead to some missing stuff.

**Comment by FredericGuilbault** [comment]
Missing deps have been added
