### ISSUE TITLE
Reduce the size taken by nativefier apps

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#62]
I’ve added the call to

hardlink

on /opt/* directories

Check my fork. 

Thanks

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Related changes found by diffing code with gitblame 
https://github.com/bareboat-necessities/lysmarine_gen/commit/fe542e756b7d7352bdf43142ba1e1b9dbe7456a0
https://github.com/bareboat-necessities/lysmarine_gen/commit/2b4293fc37669b7bacc0d200fc18d9385003d091
https://github.com/bareboat-necessities/lysmarine_gen/commit/9e6ca41864fdd6c4fc04d901e7025d4e7b3ee494

**Comment by mgrouch** [comment]
Yes
