### ISSUE TITLE
Missing window decorations in opencpn are problematic

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#67]
Missing window decorations in opencpn are problematic

We need to put them back. It's in rc.xml file.

Thanks

**Comment by mgrouch** [comment]
Also to make window toolbar icons more spread (for better usability with touchscreens) I had to increase window title font to 16pt.

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
> Missing window decorations in opencpn are problematic 

On the main window or the dialogues ?

**Comment by mgrouch** [comment]
in rc.xml, do not disable window decoration for some of apps (gtk2 ones)
