### ISSUE TITLE
In latest arm64 build wifi icon says "device is not ready"

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#70]
In latest arm64 build wifi icon says "device is not ready"

**Comment by mgrouch** [comment]
Disabling dhcpcd service fixes it

**Comment by FredericGuilbault** [comment]
raspios for arm64 is in fact a completely different OS then raspbian armhf.  Maintained by a different team and build differently. 

If I do `lsb_release -id -s`   it state raspios as `Debian`   This is the source of the problem.   

ill fix it today. thx
