### ISSUE TITLE
MenuButtons and touch do not work sporadically

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#72]
Seems to be GTK2 issue. I see it in many apps (all GTK2, ex: fbpanel, opencpn, xfce4-panel)
with hamburger icons.
tint2 is not impacted with this issue (tint2 is not GTK based)
Clicking with mouse works, touch on a touchscreen doesn't

**Comment by mgrouch** [comment]
Reported here

https://gitlab.gnome.org/GNOME/gtk/-/issues/3372

**Comment by mgrouch** [comment]
Fbpanel has to go. As long as I do not touch anything on fbpanel things work fine with touch screen. 
After few touches on fbpanel things break. Menus do not show up. Can’t switch tabs. 
I think we should have lxpanel instead. I’ve played with tint2, xfce4-panel and they all had issues too. 
lxpanel is what raspberry OS uses and I do not have any issues with touch events on it, even with arm64

**Comment by mgrouch** [comment]
And btw lxpanel is successor of fbpanel

**Comment by mgrouch** [comment]
After more test it all boils down to gtk2. We need to use OpenCPN compiled with gtk3

**Comment by mgrouch** [comment]
Opened an issue in OpenCPN

**Comment by FredericGuilbault** [comment]
since I moved to lxpanel-gtk3 it didn't happen to me. is it happening under budgie with gtk2 apps ?

**Comment by mgrouch** [comment]
gtk2 apps are the ones which seems to break it. even for other apps (gtk3). qt apps always work though with touch fine

**Comment by FredericGuilbault** [comment]
Solved by moving to awesomeWM
