### ISSUE TITLE
In onboard setting "Shrink work area" needs to be defaulted to false

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#73]
In onboard setting "Shrink work area" needs to be defaulted to false

**Comment by FredericGuilbault** [comment]
Im curious why, What is the impact ? Or the problem it solves

**Comment by mgrouch** [comment]
Try opening OpenCPN settings dialog. It’s going to end into endless loop of shrinking and expanding.

**Comment by mgrouch** [comment]
Keyboard is movable with the finger anyway. There is that button with arrows pointing 4-way. You can drag keyboard by that icon

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
Hummm I can't reproduce it, Is it happening after you made some change to the window decorations or this changes on your fork ?
 
https://github.com/lysmarine/lysmarine_gen/issues/61

**Comment by mgrouch** [comment]
It was very reproducible, by opening OpenCPN settings dialog with touch with no keyboard connected

**Comment by mgrouch** [comment]
Done in my fork
