### ISSUE TITLE
Use Budgie desktop and get rid of old GTK2 apps.

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#77]
Get rid of openbox and fbpanel.
and other GTK2 supporting apps.

**Comment by mgrouch** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=274113

**Comment by mgrouch** [comment]
Done in my fork

**Comment by FredericGuilbault** [comment]
this issue refer to https://github.com/lysmarine/lysmarine_gen/issues/16

**Comment by mgrouch** [comment]
I see you going with gtk3 lxpanel. It's ok too, but I really like budgie between two
