### ISSUE TITLE
App menu needs Reorg after migrating to budgie

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#81]
App menu needs Reorg after migrating to budgie.
Just config issue

**Comment by mgrouch** [comment]
Just want to reiterate that budgie desktop is awesome and it’s way to go

**Comment by FredericGuilbault** [comment]
lolllll got it bro XD

**Comment by mgrouch** [comment]
It needs to be set up explicitly. As soon as you inherit base ones you end up with a mess in menus.
It does mean that for every application we need .desktop file in user home directory (.local/share/applications).
I suggest having category prefixed "LysCat_" for them too so it's easier to recognize.

**Comment by FredericGuilbault** [comment]
> It does mean that for every application we need .desktop file in user home directory (.local/share/applications).
if the application are not installed under in the /home/$USER/.local/ directory neither .desktop file should. 
/usr/local/share/applications would probably be a better place.

**Comment by mgrouch** [comment]
Will it get overwritten on 
apt update; apt upgrade?

**Comment by FredericGuilbault** [comment]
not if it's a /local/ directory, 

for example: apt manage everything in /usr/bin and manual install should be in /usr/local/bin so apt can't override it.

**Comment by mgrouch** [comment]
I think I got it solved in my fork
