### ISSUE TITLE
Better compression of the OS image

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#82]
done in my fork

**Comment by mgrouch** [comment]
xz related changes

**Comment by FredericGuilbault** [comment]
I suppose you are talking about this commit ?? 

https://github.com/bareboat-necessities/lysmarine_gen/commit/2b669d1dc0197c1f91330a5ed52e4c60c20ec111

Is it substantial space saved  ?

**Comment by mgrouch** [comment]
Yes. More than 30%

**Comment by FredericGuilbault** [comment]
This commit fix it: 0563d209c5ebfc40ec2f9d6bc2e17573f2ed55ba
