### ISSUE TITLE
Package TukTuk plotter on the image too

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#86]
https://bareboat-necessities.github.io/my-bareboat/#_tuktuk_chart_plotter

**Comment by FredericGuilbault** [comment]
I was packaging tuktuk before, But it has weird bugs and huge performance problem.  
https://github.com/vokkim/tuktuk-chart-plotter/pull/17
https://github.com/vokkim/tuktuk-chart-plotter/issues/12
https://github.com/vokkim/tuktuk-chart-plotter/issues/22


And is pretty much abandoned, I don't find it but I have the souvenir of vokkim or kurky telling users to install freeboard-sk instead.

**Comment by FredericGuilbault** [comment]
Unless those bugs get fixed, it's not really a viable option IMO.
