### ISSUE TITLE
pypilot and avnav both default to port 8080 (conflict)

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#96]
pypilot and avnav both default to port 8080 (conflict)

**Comment by FredericGuilbault** [comment]
Lysmarine does not use avnav.  I don't think it's pertinent that you report here a problem about something that don't exist in this repository.

But any pull request to integrate avnav into lysmarine would be more than welcome.

Agan, I don't want to be rude or sound stubborn with this, but this is the différance between contributing to a project and forking it. For what you changed on your fork and did not got it accepted in the upstream project, your on your own.
