### ISSUE TITLE
VNC server fails to start. Password not set error in /var/log/daemon

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#98]
VNC server fails to start. Password not set error in /var/log/daemon

**Comment by FredericGuilbault** [comment]
That's strange, password is hard set in the file:
install -v    -o 1000 -g 1000 $FILE_FOLDER/passwd "/home/user/.vnc/passwd"
https://github.com/lysmarine/lysmarine_gen/blame/master/install-scripts/6-desktop/8-remoteDesktopAccess.sh

And I can't reproduce it. On the contrairy it says that it's using the password file 
![image](https://user-images.githubusercontent.com/37122999/102138331-2b3e8c00-3e2a-11eb-91f9-ca7e31a533f8.png)

**Comment by FredericGuilbault** [comment]
@mgrouch  is this something that happens only on your branch ?

**Comment by mgrouch** [comment]
It doesn't seem to happen anymore for me. Can be closed
